application.name=ms-dacs2023-backend

dacs.exceptions.code-prefix=backend

spring.application.name=backend
spring.profiles.active=@activeProfile@

server.tomcat.basedir=.
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.prefix=ms_dacs2025_access_
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.file-date-format=yyyy-MM-dd
server.tomcat.accesslog.pattern=%t %a "%r" %s (%D ms)


spring.datasource.url=jdbc:postgresql://localhost:5432/dacs_db


spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires
spring.jackson.time-zone=America/Argentina/Buenos_Aires

spring.datasource.username=dacs_user
spring.datasource.password=dacs2025
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.format_sql=true