name: Build and deploy JAR app to Azure Web App - backendd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          # Subimos solo el JAR generado
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          # Lo descargamos en una carpeta limpia para evitar conflictos de ruta
          path: ./deploy_package
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C92F20511A794B3AAEC0873304E9FCE2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3918A1831E2B4121956E331C0688C22F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E913B21A473E4EDFAFA85BF868D6C9D3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backendd'
          slot-name: 'Production'
          # Apuntamos a la carpeta donde descargamos el JAR
          package: ./deploy_package
